services:
  kafka-0:
    extends:
      file: common-services.yaml
      service: kafka
    ports:
      - "9094:9094"
    environment:
      KAFKA_CFG_NODE_ID: "0"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-0:9092,EXTERNAL://localhost:9094"
    volumes:
      - kafka-volume-0:/bitnami/kafka

  kafka-1:
    extends:
      file: common-services.yaml
      service: kafka
    ports:
      - "9095:9095"
    environment:
      KAFKA_CFG_NODE_ID: "1"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9095"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-1:9092,EXTERNAL://localhost:9095"
    volumes:
      - kafka-volume-1:/bitnami/kafka

  kafka-2:
    extends:
      file: common-services.yaml
      service: kafka
    ports:
      - "9096:9096"
    environment:
      KAFKA_CFG_NODE_ID: "2"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9096"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-2:9092,EXTERNAL://localhost:9096"
    volumes:
      - kafka-volume-2:/bitnami/kafka

  ui:
    image: provectuslabs/kafka-ui:v0.7.0
    environment:
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka-0:9092
      KAFKA_CLUSTERS_0_NAME: kraft
    ports:
      - "8080:8080"

volumes:
  kafka-volume-0:
  kafka-volume-1:
  kafka-volume-2:
